services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: event_ticketing_backend

    env_file:
      - ./backend/.env

    environment:
      DB_HOST: host.docker.internal

    ports:
      - "8001:8001"

    extra_hosts:
      - "host.docker.internal:host-gateway"

    restart: unless-stopped


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://localhost:8001

    container_name: event_ticketing_frontend

    ports:
      - "5173:80"

    depends_on:
      - backend

    restart: unless-stopped